### ISSUE TITLE
brew install clang-omp

### ISSUE THREAD

**Issue by yidawang** [IntelPNI/brainiak#81] opened 2016-07-25 23:58 UTC
In README, regarding the requirements of MacOS, "brew install clang-omp" returns "Error: No available formula with the name "clang-omp" because clang-omp has been "removed" from brew.

src: http://stackoverflow.com/questions/33668323/clang-omp-in-xcode-under-el-capitan

**Comment by xoltar** [comment] 2016-07-26 00:44
Duplicate of #74

**Closed by xoltar** 2016-07-26 00:44 UTC
